src/base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.getRoutes),
    path("rooms/", views.getRooms),
    path("room/<str:pk>/", views.getRoom),
]

src/base/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    # Room
    path("room/create/", views.createRoom, name="create-room"),
    path(
        "room/<int:room>/search-member",
        views.searchMember,
        name="room-member-search",
    ),
    path("room/<slug:slug>/", views.room, name="room"),
    path("room/<int:pk>/toggle-join/", views.toggleJoinRoom, name="toggle-room-join"),
    path(
        "room/<slug:slug>/toggle-archived/",
        views.toggleRoomArchive,
        name="toggle-room-archived",
    ),
    path("room/<slug:slug>/invite/", views.sendRoomInvite, name="invite-room"),
    path("room/<slug:slug>/update", views.updateRoom, name="update-room"),
    path("room/<int:pk>/delete", views.deleteRoom, name="delete-room"),
    path(
        "room/accept-invite/<str:token>/",
        views.acceptRoomInvite,
        name="accept-invite-room",
    ),
    path("room/<slug:slug>/settings", views.settingsRoom, name="room-settings"),
    path("room/<slug:slug>/members", views.roomMembers, name="room-members"),
    # Room Membership
    path("membership/<int:pk>/delete", views.deleteMember, name="delete-member"),
    path(
        "membership/<int:pk>/toggle-admin",
        views.toggleRoomAdmin,
        name="room-toggle-admin",
    ),
    path(
        "membership/<int:pk>/toggle-blocked",
        views.toggleRoomMemberBlock,
        name="room-toggle-blocked",
    ),
    # RoomInvitation
    path("room/<slug:slug>/invitations", views.roomInvitation, name="room-invitations"),
    path(
        "room_invitation/<int:pk>/delete",
        views.roomInvitationDelete,
        name="delete-invitation",
    ),
    # Message
    path("room/<int:room_id>/add-message", views.addMessage, name="room-add-message"),
    path(
        "message/<int:pk>/reaction",
        views.toggleMessageReaction,
        name="message-reaction",
    ),
    path("message/<int:pk>/delete", views.deleteMessage, name="delete-message"),
    path("message/<int:pk>/reply", views.addMessageReply, name="message-reply"),
    path("message/<int:pk>/", views.showMessage, name="message-show"),
    # Topic
    path("topics/", views.topicsPage, name="topics"),
    path("topics/search-topic", views.searchTopic, name="search-topic"),
    #
    path("activity/", views.activityPage, name="activity"),
]

src/accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django_softdelete.models import SoftDeleteManager, SoftDeleteModel


class CustomUserManager(UserManager, SoftDeleteManager):
    pass


class User(SoftDeleteModel, AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=False)
    bio = models.TextField(null=True)

    avatar = models.URLField(max_length=200, default="https://avatars.dicebear.com/api/bottts/default.svg")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects = CustomUserManager()

    def __str__(self):
        return self.username

src/base/models.py
from django.db import models
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from django_softdelete.models import SoftDeleteModel
from mdeditor.fields import MDTextField

from accounts.models import User


class Topic(SoftDeleteModel):
    name = models.CharField(max_length=200, blank=False, null=False)
    slug = AutoSlugField(populate_from=["name"])
    description = models.TextField(null=True, blank=True)
    github_url = models.URLField(null=True, blank=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.name)
    #     return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Room(SoftDeleteModel):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="host")
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    members = models.ManyToManyField(User, blank=True, through="Membership")

    name = models.CharField(max_length=200, blank=False, null=False)
    slug = AutoSlugField(populate_from=["name"])
    description = models.TextField(null=True, blank=True)

    TYPES = [
        ("public", "Public"),
        ("private", "Private"),
    ]

    type = models.TextField(null=False, choices=TYPES, default="public")

    is_archived = models.BooleanField(default=False)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.name)
    #     return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("room", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    is_admin = models.BooleanField(default=False)

    is_blocked = models.BooleanField(default=False)
    blocked_at = models.DateTimeField(null=True, blank=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"'{self.user.username}' in room '{self.room.name}'"


class Message(SoftDeleteModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    parent = models.ForeignKey(
        "self",
        related_name="replies",
        related_query_name="message",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    body = MDTextField()

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]
        permissions = (
            ("delete_msg", "Delete Msg"),
            ("reply_msg", "Reply Msg"),
        )

    def __str__(self):
        return self.body[0:50]


class ReactionType(models.Model):
    name = models.CharField(max_length=70, null=False, blank=False)

    updated = models.DateTimeField(blank=True, null=True, auto_now=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def __str__(self):
        return f"{self.name}"


class Reaction(models.Model):
    reaction_type = models.ForeignKey(ReactionType, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    updated = models.DateTimeField(blank=True, null=True, auto_now=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def __str__(self):
        return f"{self.reaction_type.name} to {self.user.username}'s message"


class RoomInvitation(models.Model):
    inviter = models.ForeignKey(User, related_name="inviter", on_delete=models.CASCADE)
    invitee = models.ForeignKey(User, related_name="invitee", on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    token = models.CharField(max_length=100, null=False, blank=False)
    is_accepted = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.room.name} - {self.inviter.username}"

src/base/forms.py
# from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from mdeditor.fields import MDTextFormField

from .models import Message, Room


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = "__all__"
        exclude = ["host", "members"]


class MessageForm(ModelForm):
    body = MDTextFormField(label="")

    class Meta:
        model = Message
        fields = ["body"]
        # exclude = ['user','room']

src/base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(["GET"])
def getRoutes(request):
    routes = ["GET /api", "GET /api/rooms", "GET /api/rooms/:id"]
    return Response(routes)


@api_view(["GET"])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(["GET"])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

src/base/templates/base/_spinner.html
<div id="spinner"
     class="htmx-indicator m-12 inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-current border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]"
     role="status">
    <span class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">
        Loading...
    </span>
</div>

src/base/templates/base/converstion_component.html
<div class="room__conversation">
    <div class="threads scroll" id="messages-list">
        {% for message in room.message_set.all %}
            {% include "base/_message.html" %}
        {% empty %}
            <span>No Messages Yet !</span>
        {% endfor %}
    </div>
</div>
{% if request.user.is_authenticated %}
    {% block extra_scripts %}
        <script>
            document.addEventListener(
                "click",
                function(event) {
                    var target = event.target;
                    var replyForm;
                    if (target.matches("[data-toggle='reply-form']")) {
                        replyForm = document.getElementById(target.getAttribute("data-target"));
                        replyForm.classList.toggle("d-none");
                    }
                },
                false
            );
        </script>
    {% endblock extra_scripts %}
{% endif %}

src/base/templates/base/invite_user_form.html
{% extends "main.html" %}
{% load i18n %}
{% block title %}
    <title>Send Invitation</title>
{% endblock title %}
{% block content %}
    <main class="my_container">
        <div class="auth">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <h3>Invite User</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <p>Please add an email below. The user will receive an email with instructions.</p>
                    <br />
                    <form id="invite-form"
                          method="post"
                          action="{% url 'invite-room' room.slug %}"
                          autocomplete="off">
                        {% csrf_token %}
                        <div class="form__group relative">
                            <label for="id_email">Invite:</label>
                            <input type="text"
                                   name="email"
                                   id="id_email"
                                   value="{{ form.email.value }}"
                                   class="form-control validate-email"
                                   placeholder="Start typing the user email ..."
                                   hx-post="{% url 'search-user' %}"
                                   hx-trigger="keyup changed delay:300ms"
                                   hx-target="#users-list"
                                   required>
                            <div class="absolute rounded-b bg-bg border border-dark-medium w-full"
                                 id="users-list"></div>
                        </div>
                        <div class="form__group">
                            {% for error in form.email.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}
                            {{ success_message }}
                        </div>
                        <input type="submit"
                               value="Send Invitation"
                               class="btn btn--main generic-ajax-submit">
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

src/base/templates/base/room.html
{% extends "main.html" %}
{% load static %}
{% block extra_heads %}
    <link rel="stylesheet" href="{% static "styles/default.css" %}" />
    <link rel="stylesheet" href="{% static "styles/markdown.css" %}" />
{% endblock extra_heads %}
{% block meta_tags %}
    <title>{{ room.name }}</title>
    <meta name="title" content="{{ room.title }}" head-key="title" />
    <meta name="description"
          content="{{ room.description.strip|slice:":100" }}"
          head-key="description" />
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:title" content="{{ room.title }}" />
    <meta property="og:description"
          content="{{ room.description.strip|slice:":100" }}" />
    <meta property="og:image"
          content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}/media/room_thumb/{{ room.slug }}.png" />
    {% comment %}
  <meta property="og:image" content="https://blog.shahryartayeb.com/generate_banner?text={{room.slug}}" />
    {% endcomment %}
    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content="{{ request.build_absolute_uri }}" />
    <meta property="twitter:title" content="{{ room.title }}" />
    <meta property="twitter:description"
          content="{{ room.description.strip|slice:":100" }}" />
    <meta property="twitter:image"
          content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}/media/room_thumb/{{ room.slug }}.png" />
{% endblock meta_tags %}
{% block content %}
    <main class="profile-page layout layout--2">
        <div class="my_container ">
            <!-- Room Start -->
            <div class="room ">
                <div class="room__top">
                    <div class="room__topLeft items-center">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <img height="30"
                                 width="30"
                                 src="{% static 'images/icons/arrow-left.svg' %}"
                                 alt="left-arrow">
                        </a>
                        <h3>Study Room</h3>
                        {% if room.type == 'private' %}
                            {% comment %} <span class="roomListRoom__topic">{{room.type}}</span> {% endcomment %}
                            <button class="bg-dark-medium px-4 py-2 rounded-full border border-dark-light"
                                    type="submit">
                                <img height="30"
                                     width="30"
                                     src="{% static 'images/icons/lock-2.svg' %}"
                                     alt="lock">
                            </button>
                        {% endif %}
                    </div>
                    <div class="room__topRight">
                        {% if room.host == request.user or is_admin %}
                            <a href="{% url 'room-settings' room.slug %}"
                               class="room__topics btn bg-dark-medium">Settings</a>
                            <a href="{% url 'update-room' room.slug %}"
                               class="room__topics btn bg-dark-medium">
                                <img height="30"
                                     width="30"
                                     src="{% static 'images/icons/pen.svg' %}"
                                     alt="pen">
                            </a>
                        {% endif %}
                        {% if not request.user.id == room.host_id %}
                            <form hx-post="{% url 'toggle-room-join' room.id %}"
                                  hx-indicator=".progress">
                                {% csrf_token %}
                                <button type="submit" class="room__topics  btn bg-dark-medium">
                                    {% if is_joined %}
                                        Leave Room
                                    {% else %}
                                        Join Room
                                    {% endif %}
                                </button>
                            </form>
                        {% endif %}
                        {% if room.host_id == request.user.id or is_admin %}
                            <a href="{% url 'invite-room' room.slug %}"
                               class="room__topics btn bg-dark-medium"
                               id="invite-user-btn">Invite Users</a>
                        {% endif %}
                    </div>
                </div>
                <div class="room__box scroll">
                    <div class="room__header scroll">
                        <div class="room__info">
                            <h3>{{ room.name }}</h3>
                            <span>{{ room.created|timesince }} ago</span>
                        </div>
                        <div class="room__hosted">
                            <p>Hosted By</p>
                            <a href="{% url 'user-public-profile' room.host.username %}"
                               class="room__author w-fit">
                                <div class="avatar avatar--small">
                                    <img height="30" width="30" src="{{ room.host.avatar }}" alt="user-avatar" />
                                </div>
                                <span>@{{ room.host.username }}</span>
                            </a>
                        </div>
                        <div class="room__details my-2">{{ room.description }}</div>
                        <span class="room__topics bg-dark-medium my-2">{{ room.topic }}</span>
                    </div>
                    {% comment %} The message {% endcomment %}
                    {% if request.user.is_authenticated and not is_blocked and not room.is_archived %}
                        <div class="room__message">
                            <form hx-post="{% url 'room-add-message' room.id %}"
                                  hx-target="#messages-list"
                                  hx-swap="afterbegin"
                                  hx-indicator=".progress"
                                  hx-ext="disable-element"
                                  hx-disable-element="#sumbit-btn-message"
                                  class="reply-form  bg-bg border border-gray-600 rounded-xl ">
                                {% csrf_token %}
                                {{ msg_form.media }}
                                {{ msg_form.as_p }}
                                <div class="flex items-center justify-between gap-3 border-t border-dark  p-5">
                                    <p class="text-gray-400">Supports Markdown</p>
                                    <button type="submit"
                                            class="disabled:bg-gray btn btn--dark hover:bg-dark-medium"
                                            id="sumbit-btn-message"
                                            hx-disable-element="self">Add Message</button>
                                </div>
                            </form>
                        </div>
                    {% endif %}
                    {% include "base/converstion_component.html" %}
                </div>
            </div>
            <!--   Members -->
            <div class="sticky_right_panel sticky_panel  ">
                <h3 class="participants__top">
                    Latest Members <span>({{ room.membership_set.all.count }} Joined)</span>
                </h3>
                <div class="participants__list scroll">
                    {% for membership in room.membership_set.all %}
                        <a 
                            href="{% url 'user-public-profile' membership.user.username %}"
                           class="participant {% if membership.is_admin %}bg-dark-light p-3 rounded-md{% endif %}">
                            <div class="avatar avatar--medium">
                                <img height="30"
                                     width="30"
                                     src="{{ membership.user.avatar }}"
                                     alt="user-avatar" />
                            </div>
                            <p>
                                {{ membership.user.username }}
                                <span>@{{ membership.user.username }}</span>
                            </p>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <!--  End -->
        </div>
    </main>
{% endblock content %}

src/base/templates/base/room_settings.html
{% extends "base/room_settings_base.html" %}
{% load static %}
{% block title %}
    <title>Settings: Room Details</title>
{% endblock title %}
{% block settings_content %}
    <section class="bg-dark">
        <div class="participants__top flex justify-between">
            <h3>Room Details</h3>
        </div>
        <div class="p-10">
            <div class="mb-10">
                <h4 class="mb-5 text-2xl font-medium">{{ room.name }}</h4>
                <p class="text-gray-500">{{ room.description }}</p>
            </div>
            <div class="flex flex-col gap-16">
                <div class="flex justify-between items-center border-b border-dark-medium pb-5 ">
                    <div class="space-y-2">
                        <span class="font-medium">Type</span>
                        <p class="text-xl"></p>
                    </div>
                    <p class="roomListRoom__topic  ">{{ room.type }}</p>
                </div>
                <div class="flex justify-between items-center border-b border-dark-medium pb-5 ">
                    <div class="space-y-2">
                        <span class="font-medium">Created At</span>
                        <p class="text-xl"></p>
                    </div>
                    <p>{{ room.created|timesince }}</p>
                </div>
                <div class="flex justify-between items-center border-b border-dark-medium pb-5 ">
                    <div class="space-y-2">
                        <span class="font-medium">Topic</span>
                        <p class="text-xl"></p>
                    </div>
                    <p class="roomListRoom__topic ">{{ room.topic }}</p>
                </div>
                <div class="flex justify-between items-center border-b border-dark-medium pb-5 ">
                    <div class="space-y-2">
                        <span class="font-medium">Host</span>
                        <p class="text-xl"></p>
                    </div>
                    <a href="{% url 'user-public-profile' room.host.username %}"
                       class="participant mb-0 flex gap-5">
                        <div class="avatar avatar--medium">
                            <img src="{{ room.host.avatar }}" height="35" width="35" alt="user-avatar" />
                        </div>
                        <p>
                            {{ room.host.name }}
                            <span>@{{ room.host.username }}</span>
                        </p>
                    </a>
                </div>
            </div>
            <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-5 my-16">
                <div class="group  rounded-md relative bg-white dark:bg-gray-800 transition hover:z-[1] hover:shadow-2xl hover:shadow-gray-600/10">
                    <div class="relative space-y-8 py-12 p-8">
                        <img src="https://cdn-icons-png.flaticon.com/512/4341/4341139.png"
                             class="w-12"
                             width="512"
                             height="512"
                             alt="burger illustration">
                        <div class="space-y-2">
                            <h5 class="text-xl font-semibold text-gray-700 dark:text-white transition group-hover:text-secondary">
                                {{ room.members.count }}
                            </h5>
                            <p class="text-gray-600 dark:text-gray-300">
                                Total <b>members</b> of the room.
                            </p>
                        </div>
                        <a href="{% url 'room-members' room.slug %}"
                           class="flex items-center justify-between group-hover:text-secondary">
                            <span class="text-sm">See more</span>
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 24 24"
                                 fill="currentColor"
                                 class="w-5 h-5 -translate-x-4 text-2xl opacity-0 transition duration-300 group-hover:translate-x-0 group-hover:opacity-100">
                                <path fill-rule="evenodd" d="M12.97 3.97a.75.75 0 011.06 0l7.5 7.5a.75.75 0 010 1.06l-7.5 7.5a.75.75 0 11-1.06-1.06l6.22-6.22H3a.75.75 0 010-1.5h16.19l-6.22-6.22a.75.75 0 010-1.06z" clip-rule="evenodd">
                                </path>
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="group rounded-md  relative bg-white dark:bg-gray-800 transition hover:z-[1] hover:shadow-2xl hover:shadow-gray-600/10">
                    <div class="relative space-y-8 py-12 p-8">
                        <img src="https://cdn-icons-png.flaticon.com/512/4341/4341139.png"
                             class="w-12"
                             width="512"
                             height="512"
                             alt="burger illustration">
                        <div class="space-y-2">
                            <h5 class="text-xl font-semibold text-gray-700 dark:text-white transition group-hover:text-secondary">
                                {{ room.roominvitation_set.count }}
                            </h5>
                            <p class="text-gray-600 dark:text-gray-300">
                                Total <b>Invitations</b> of the room.
                            </p>
                        </div>
                        <a href="{% url 'room-invitations' room.slug %}"
                           class="flex items-center justify-between group-hover:text-secondary">
                            <span class="text-sm">See more</span>
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 24 24"
                                 fill="currentColor"
                                 class="w-5 h-5 -translate-x-4 text-2xl opacity-0 transition duration-300 group-hover:translate-x-0 group-hover:opacity-100">
                                <path fill-rule="evenodd" d="M12.97 3.97a.75.75 0 011.06 0l7.5 7.5a.75.75 0 010 1.06l-7.5 7.5a.75.75 0 11-1.06-1.06l6.22-6.22H3a.75.75 0 010-1.5h16.19l-6.22-6.22a.75.75 0 010-1.06z" clip-rule="evenodd">
                                </path>
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="group rounded-md  relative bg-white dark:bg-gray-800 transition hover:z-[1] hover:shadow-2xl hover:shadow-gray-600/10">
                    <div class="relative space-y-8 py-12 p-8">
                        <img src="https://cdn-icons-png.flaticon.com/512/4341/4341139.png"
                             class="w-12"
                             width="512"
                             height="512"
                             alt="burger illustration">
                        <div class="space-y-2">
                            <h5 class="text-xl font-semibold text-gray-700 dark:text-white transition group-hover:text-secondary">
                                {{ room.message_set.count }}
                            </h5>
                            <p class="text-gray-600 dark:text-gray-300">
                                Total <b>messages</b> in the room
                            </p>
                        </div>
                        <a href="#"
                           class="flex items-center justify-between group-hover:text-secondary">
                            <span class="text-sm">See more</span>
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 24 24"
                                 fill="currentColor"
                                 class="w-5 h-5 -translate-x-4 text-2xl opacity-0 transition duration-300 group-hover:translate-x-0 group-hover:opacity-100">
                                <path fill-rule="evenodd" d="M12.97 3.97a.75.75 0 011.06 0l7.5 7.5a.75.75 0 010 1.06l-7.5 7.5a.75.75 0 11-1.06-1.06l6.22-6.22H3a.75.75 0 010-1.5h16.19l-6.22-6.22a.75.75 0 010-1.06z" clip-rule="evenodd">
                                </path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <div class="flex flex-col gap-16">
                <div class="flex justify-between items-center border-b border-dark-medium pb-5 ">
                    <div class="space-y-2">
                        <span class="font-medium">Archive Room</span>
                        <p class="text-xl">Archiving the room will close the room for new messages/replies and joining the room.</p>
                    </div>
                    <div id="archive-toggle">{% include "base/partials/toggle_archived.html" %}</div>
                </div>
                <div class="flex justify-between items-center border-b border-dark-medium pb-5 ">
                    <div class="space-y-2">
                        <span class="font-medium">Delete Room</span>
                        <p class="text-xl">Deleting a room will delete all its members and messages/replies.</p>
                    </div>
                    <a href="{% url 'delete-room' room.id %}"
                       class="room__topics btn bg-red-700 flex gap-3">
                        <img src="{% static 'images/icons/times.svg' %}"
                             height="20"
                             width="20"
                             alt="close">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </section>
{% endblock settings_content %}